[package]
name = "numpy-type-desc"
version = "0.1.0"
authors = ["Ivan Smirnov <rust@ivan.smirnov.ie>"]
edition = "2018"
rust-version = "1.48"

[dependencies]
pyo3 = "^0.15.1"
numpy = "^0.15.1"
pyo3-type-desc = { path = "..", features = ["complex"] }
num-complex = "0.4"
num-traits = "0.2"
